# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charlie6th.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about the birthing and raising of our son, Charlie.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://charlie6th.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# Collections
collections:
  - authors

# Prose Config
prose:
  rooturl: "_posts"
  media: "assets/uploads"
  siteurl: "https://charlie6th.com"
  metadata:
    _posts:
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          value: "johnny"
          options:
            - name: "Johnny"
              value: "Johnny"
            - name: "Jackie"
              value: "Jackie"
